name: Build and Upload Artifacts
on:
  push:
    branches: [main]
jobs:
  build_windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19
    - name: Build and Test
      run: |
        set GOOS=windows 
        set GOARCH=amd64 
        go build -o myapp.exe
        go test ./...
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: myapp-windows-amd64
        path: myapp.exe

  build_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19
    - name: Build and Test
      run: |
        go build -o myapp
        go test ./...
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: myapp-linux-amd64
        path: myapp

  build_macos:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19
    - name: Build and Test
      run: |
        GOOS=darwin GOARCH=amd64
        go build -o myapp
        go test ./...
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: myapp-linux-macos
        path: myapp