name: Build and Release
on:
  push:
    branches:
      - main
jobs:
  build-and-release:
    runs-on: windows-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19
    - name: Build
      run:|
      set GOOS=windows 
      set GOARCH=amd64 
      go build -o 2dol.exe
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: 2dol.exe
        path: 2dol.exe
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
      with:
        tag_name: v1.0.0
        release_name: Release v1.0.0
        body: |
          This is the first release of 2dol.
          It includes the following changes:
          - Feature 1
          - Feature 2
        draft: false
        prerelease: false
    - name: Upload Artifact to Release
      uses: actions/upload-release-asset@v1
      env:
        GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./2dol.exe
        asset_name: 2dol.exe
        asset_content_type: application/octet-stream
