name: Build and Upload Artifacts
on:
  push:
    branches: [main]
jobs:
  build_windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19
    - name: Build and Test
      run: |
        set GOOS=windows 
        set GOARCH=amd64 
        go build -o 2dol.exe
        go test ./...
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: 2dol-windows-amd64
        path: 2dol.exe

  build_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19
    - name: Build and Test
      run: |
        go build -o 2dol
        go test ./...
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: 2dol-linux-amd64
        path: 2dol

  build_macos:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19
    - name: Build and Test
      run: |
        GOOS=darwin GOARCH=amd64
        go build -o 2dol
        go test ./...
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: 2dol-linux-macos
        path: 2dol